### ISSUE TITLE
Executing "./tools/k8s-helper.sh setup-namespaces" ----> error: Task 'artifactId' not found in root project 'jenkins'.

### ISSUE THREAD

**Issue by davsuapas** [CloudPipelines/jenkins#1]
Hi,
Executing "./tools/k8s-helper.sh setup-namespaces" ----> error: Task 'artifactId' not found in root project 'jenkins'.
I think that the problem is because now is used "export -f retrieveAppName" into pipeline-gradle.sh file, therefore is invalidated the function defined into k8s-helper.sh file

**Comment by davsuapas** [comment]
Now I get error "substituteVariables: command not found", because setup-namespaces needs substituteVariables function to work and this one is found pipeline.sh. Sorry

**Comment by marcingrzejszczak** [comment]
Keep on going ;)

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/CloudPipelines/jenkins/commit/d5f07c320efec7d0f8b60644839835a775beeebe

**Comment by davsuapas** [comment]
Now, no execute createnamespace. It must have a problem with retrieveAppName function. The code execution finish in  "$(retrieveAppName)" of the pipeline.sh

if [[ "${PROJECT_NAME}" == "" || "${PROJECT_NAME}" == "null" ]]; then
	PROJECT_NAME="$(retrieveAppName)"
fi

**Log**:

Picked PAAS is [k8s]
Current environment is [PROD]
Project name []
No pipeline descriptor [cloud-pipelines.yml] found. Will fallback to [sc-pipelines.yml]
No legacy pipeline descriptor [sc-pipelines.yml] found - will not deploy any services
Pipeline descriptor missing
No descriptor or module found for project with name [], project setup [SINGLE_REPO]
Language needs to be guessed from the sources
Failed to guess the language type!
No projectType/pipeline-projectType.sh found

**Comment by davsuapas** [comment]
It may be that I am doing something wrong

**Comment by marcingrzejszczak** [comment]
Have you pulled the latest changes? Cause now it should fetch the values from `tools/k8s/build.gradle`

**Comment by davsuapas** [comment]
The same is better to get this util function (substituteVariables) out of pipeline.sh into other script and call her from both

**Comment by marcingrzejszczak** [comment]
`substituteVariables` is in `pipeline-k8s.sh` not in `pipeline.sh`

**Comment by davsuapas** [comment]
Yes, I execute "./tools/k8s-helper.sh setup-namespaces" from command line.

**Comment by marcingrzejszczak** [comment]
I've finally managed to execute this locally and now it should work :)

**Comment by davsuapas** [comment]
Now work. Thanks
