### ISSUE TITLE
Demo jenkins login

### ISSUE THREAD

**Issue by rahulaga** [CloudPipelines/jenkins#6]
I started the jenkins provided here https://hub.docker.com/r/springcloud/spring-cloud-pipeline-jenkins/

What is the jenkins login for this image?

Thanks

**Comment by marcingrzejszczak** [comment]
which username and password are you referring to?

**Comment by rahulaga** [comment]
After I start that image and goto localhost:8080 its asking for a username/password.

Did this following jenkins install page:
```docker run \
  -u root \
  -d \
  -p 8080:8080 \
  -p 50000:50000 \
  -v jenkins-data:/var/jenkins_home \
  -v /var/run/docker.sock:/var/run/docker.sock \
  springcloud/spring-cloud-pipeline-jenkins

**Comment by marcingrzejszczak** [comment]
So if you build the docker image from sources, what you can do is uncomment this line https://github.com/CloudPipelines/jenkins/blob/master/demo/Dockerfile#L96 and run this script https://github.com/CloudPipelines/jenkins/blob/master/demo/start.sh and it works fine

Can you paste the exact command that you're running? I'm more than certain that you have the password printed in the log.

**Comment by marcingrzejszczak** [comment]
I've executed `docker run -u root -p 8080:8080 -p 50000:50000 -v /var/run/docker.sock:/var/run/docker.sock springcloud/spring-cloud-pipeline-jenkins` and I'm logging to jenkins at `localhost:8080` without any username and password

**Comment by rahulaga** [comment]
Thanks! It was the jenkins-data from my previous attempt. Not sure why it did not login though.
