### ISSUE TITLE
Generating standalone Jenkinsfile

### ISSUE THREAD

**Issue by rahulaga** [CloudPipelines/jenkins#7]
This is a question around usage not answered in docs and not a bug. 

What I would like to do is generate the opinionated Jenkinsfile for my existing repo (Spring boot/gradle project) and deploy to my existing Jenkins. How can I do that? 
Also how does the "seed" job get added to an existing Jenkins installation.

Ideally I should be able to run everything locally and not need any github etc that the demo projects are asking for.

Appreciate any advice.

**Comment by marcingrzejszczak** [comment]
Either you add the seed job manually to your jenkins installation that generates jenkinsfile (https://github.com/CloudPipelines/jenkins/blob/master/declarative-pipeline/jobs/jenkins_pipeline_jenkinsfile_sample.groovy) with an example of a jenkinsfile (https://github.com/CloudPipelines/jenkins/blob/master/declarative-pipeline/src/main/resources/Jenkinsfile-sample) or you can copy it as we do when you start your container (example of a meta-seed job generating the seed job for a jenkinsfile based pipeline - https://github.com/CloudPipelines/jenkins/blob/master/demo/seed/jenkins_pipeline.groovy#L355-L425) and where it's referenced (https://github.com/CloudPipelines/jenkins/blob/master/demo/seed/init.groovy#L181-L184). So the `init.groovy` file gets copied to the image and is executed upon startup. That means that the meta seed job will be executed and it will generate the seed jobs.
